import type { Metadata } from "next";
import Link from "next/link";
// import localFont from "next/font/local";
// import "./globals.css";
// import "./combined-v5.css"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Learning NextJS with TypeScript and ReactJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div>
          <Link href={`/`}>Home</Link> <br />
        </div> */}
        {children}
      </body>
    </html>
  );
}
