import type { Metadata } from "next";
import Link from "next/link";
// import localFont from "next/font/local";
// import "./globals.css";
// import "./combined-v5.css"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Learning NextJS with TypeScript and ReactJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div>
          <Link href={`/`}>Home</Link> <br />
        </div> */}
        <h1 style={{ color: "red" }}>
          Halting (or Stopping) all development, enhancements, and bug fixes
          until further (or next) instructions from the CEO of SPP International
          Pvt Ltd. <br />
          Please refer below link for details:{" "}
          <a
            href="http://localhost:3002/notifications"
            target="_blank"
            rel="noopener noreferrer"
          >
            Click here
          </a>
        </h1>

        {children}
      </body>
    </html>
  );
}
