version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/mongodb_test
      - PORT= 3003
      - REACT_PORT= 3002
    # depends_on:
    #   - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT= 3002
      - BACKEND_APPLICATION_BASE_URL= http://127.0.0.1:3003

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data:
